"""initial production schema

Revision ID: 08f6ea886096
Revises: 
Create Date: 2026-06-16 08:58:54.971896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f6ea886096'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('registered_name', sa.String(length=150), nullable=True),
    sa.Column('business_address', sa.String(length=255), nullable=True),
    sa.Column('tin', sa.String(length=20), nullable=True),
    sa.Column('branch_code', sa.String(length=5), nullable=True),
    sa.Column('machine_identification_number', sa.String(length=50), nullable=True),
    sa.Column('machine_serial_number', sa.String(length=100), nullable=True),
    sa.Column('software_license_number', sa.String(length=100), nullable=True),
    sa.Column('accreditation_number', sa.String(length=100), nullable=True),
    sa.Column('accreditation_date_issued', sa.Date(), nullable=True),
    sa.Column('accreditation_valid_until', sa.Date(), nullable=True),
    sa.Column('ptu_number', sa.String(length=100), nullable=True),
    sa.Column('ptu_date_issued', sa.Date(), nullable=True),
    sa.Column('accredited_supplier_name', sa.String(length=150), nullable=True),
    sa.Column('accredited_supplier_address', sa.String(length=255), nullable=True),
    sa.Column('accredited_supplier_tin', sa.String(length=20), nullable=True),
    sa.Column('software_version', sa.String(length=50), nullable=True),
    sa.Column('reset_counter', sa.Integer(), nullable=True),
    sa.Column('business_day_cutoff', sa.String(length=5), nullable=True),
    sa.Column('vat_status', sa.String(length=10), nullable=True),
    sa.Column('sells_meat', sa.Boolean(), nullable=True),
    sa.Column('sells_fish', sa.Boolean(), nullable=True),
    sa.Column('sells_retail', sa.Boolean(), nullable=True),
    sa.Column('sells_veggies', sa.Boolean(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('last_invoice_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('before_state', sa.Text(), nullable=True),
    sa.Column('after_state', sa.Text(), nullable=True),
    sa.Column('reverted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.String(length=150), nullable=True),
    sa.Column('terminal_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash')
    )
    op.create_table('e_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=6), nullable=False),
    sa.Column('invoice_type', sa.String(length=10), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('cashier_name', sa.String(length=150), nullable=True),
    sa.Column('payment_mode', sa.String(length=20), nullable=True),
    sa.Column('cash_tendered', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('change_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('buyer_name', sa.String(length=150), nullable=True),
    sa.Column('buyer_address', sa.String(length=255), nullable=True),
    sa.Column('buyer_tin', sa.String(length=20), nullable=True),
    sa.Column('buyer_business_style', sa.String(length=150), nullable=True),
    sa.Column('seller_snapshot_json', sa.Text(), nullable=False),
    sa.Column('vatable_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vat_exempt_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zero_rated_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sspt_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('percentage_tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('discount_id_no', sa.String(length=50), nullable=True),
    sa.Column('discount_beneficiary_name', sa.String(length=150), nullable=True),
    sa.Column('discount_beneficiary_tin', sa.String(length=20), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('voided_reason', sa.Text(), nullable=True),
    sa.Column('voided_by', sa.String(length=150), nullable=True),
    sa.Column('synced', sa.Boolean(), nullable=True),
    sa.Column('reprint_count', sa.Integer(), nullable=True),
    sa.Column('last_reprinted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'invoice_number', name='uq_invoice_user_number')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('cut_type', sa.String(length=100), nullable=True),
    sa.Column('pricing_type', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('stock_quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('low_stock_threshold', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('tax_classification', sa.String(length=15), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('products_supplied', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('x_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vatable_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vat_exempt_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zero_rated_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=True),
    sa.Column('void_count', sa.Integer(), nullable=True),
    sa.Column('starting_invoice_no', sa.String(length=6), nullable=True),
    sa.Column('ending_invoice_no', sa.String(length=6), nullable=True),
    sa.Column('cash_sales', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('reset_counter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('z_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vatable_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vat_exempt_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zero_rated_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=True),
    sa.Column('void_count', sa.Integer(), nullable=True),
    sa.Column('accumulated_grand_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('z_counter', sa.Integer(), nullable=True),
    sa.Column('starting_invoice_no', sa.String(length=6), nullable=True),
    sa.Column('ending_invoice_no', sa.String(length=6), nullable=True),
    sa.Column('cash_sales', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('reset_counter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_line_classification', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_items')
    op.drop_table('z_readings')
    op.drop_table('x_readings')
    op.drop_table('suppliers')
    op.drop_table('products')
    op.drop_table('invoices')
    op.drop_table('e_journal')
    op.drop_table('audit_log')
    op.drop_table('users')
    # ### end Alembic commands ###
