"""add BIR compliance controls

Revision ID: 65a1facfae95
Revises: 
Create Date: 2026-06-15 19:30:16.260371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a1facfae95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('terminal_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('event_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('previous_hash', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_audit_event_hash', ['event_hash'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cashier_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('payment_mode', sa.String(length=20), nullable=True, server_default='cash'))
        batch_op.add_column(sa.Column('cash_tendered', sa.Numeric(precision=12, scale=2), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('change_amount', sa.Numeric(precision=12, scale=2), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('buyer_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('buyer_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('buyer_tin', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('buyer_business_style', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('seller_snapshot_json', sa.Text(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('voided_by', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('reprint_count', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('last_reprinted_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_invoice_user_number', ['user_id', 'invoice_number'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_code', sa.String(length=5), nullable=True, server_default='00000'))
        batch_op.add_column(sa.Column('machine_identification_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('machine_serial_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('software_license_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('accreditation_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('accreditation_date_issued', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('accreditation_valid_until', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('ptu_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ptu_date_issued', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('accredited_supplier_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('accredited_supplier_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('accredited_supplier_tin', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('software_version', sa.String(length=50), nullable=True, server_default='1.0.0'))
        batch_op.add_column(sa.Column('reset_counter', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('business_day_cutoff', sa.String(length=5), nullable=True, server_default='00:00'))

    with op.batch_alter_table('x_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_sales', sa.Numeric(precision=14, scale=2), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('reset_counter', sa.Integer(), nullable=True, server_default='0'))

    with op.batch_alter_table('z_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_sales', sa.Numeric(precision=14, scale=2), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('reset_counter', sa.Integer(), nullable=True, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('z_readings', schema=None) as batch_op:
        batch_op.drop_column('reset_counter')
        batch_op.drop_column('cash_sales')

    with op.batch_alter_table('x_readings', schema=None) as batch_op:
        batch_op.drop_column('reset_counter')
        batch_op.drop_column('cash_sales')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('business_day_cutoff')
        batch_op.drop_column('reset_counter')
        batch_op.drop_column('software_version')
        batch_op.drop_column('accredited_supplier_tin')
        batch_op.drop_column('accredited_supplier_address')
        batch_op.drop_column('accredited_supplier_name')
        batch_op.drop_column('ptu_date_issued')
        batch_op.drop_column('ptu_number')
        batch_op.drop_column('accreditation_valid_until')
        batch_op.drop_column('accreditation_date_issued')
        batch_op.drop_column('accreditation_number')
        batch_op.drop_column('software_license_number')
        batch_op.drop_column('machine_serial_number')
        batch_op.drop_column('machine_identification_number')
        batch_op.drop_column('branch_code')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('uq_invoice_user_number', type_='unique')
        batch_op.drop_column('last_reprinted_at')
        batch_op.drop_column('reprint_count')
        batch_op.drop_column('voided_by')
        batch_op.drop_column('seller_snapshot_json')
        batch_op.drop_column('buyer_business_style')
        batch_op.drop_column('buyer_tin')
        batch_op.drop_column('buyer_address')
        batch_op.drop_column('buyer_name')
        batch_op.drop_column('change_amount')
        batch_op.drop_column('cash_tendered')
        batch_op.drop_column('payment_mode')
        batch_op.drop_column('cashier_name')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint('uq_audit_event_hash', type_='unique')
        batch_op.drop_column('previous_hash')
        batch_op.drop_column('event_hash')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('terminal_id')
        batch_op.drop_column('actor')

    # ### end Alembic commands ###
