"""add statutory discount beneficiary details

Revision ID: b0685882aad9
Revises: 65a1facfae95
Create Date: 2026-06-15 19:41:45.679923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0685882aad9'
down_revision = '65a1facfae95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_beneficiary_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('discount_beneficiary_tin', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('discount_beneficiary_tin')
        batch_op.drop_column('discount_beneficiary_name')

    # ### end Alembic commands ###
