"""separate registered taxpayer name

Revision ID: bb24f2e2f588
Revises: c90e9e20ee3d
Create Date: 2026-06-15 19:57:07.080811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb24f2e2f588'
down_revision = 'c90e9e20ee3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_name', sa.String(length=150), nullable=True))

    op.execute(
        "UPDATE users SET registered_name = business_name "
        "WHERE registered_name IS NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('registered_name')

    # ### end Alembic commands ###
